# Generated by Django 5.2.8 on 2026-02-12 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 26, 7, 37, 10, 973415, tzinfo=datetime.timezone.utc)),
        ),
    ]
