# Generated by Django 5.2.8 on 2026-03-13 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 6, 51, 32, 251602, tzinfo=datetime.timezone.utc)),
        ),
    ]
