# Generated by Django 5.2.8 on 2026-03-14 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 28, 3, 10, 32, 856425, tzinfo=datetime.timezone.utc)),
        ),
    ]
