# Generated by Django 5.2.8 on 2026-03-14 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_borrowrecord_is_approved_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 28, 3, 29, 40, 317931, tzinfo=datetime.timezone.utc)),
        ),
    ]
